name: build-on-windows-msbuild-x86

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout from git
      uses: actions/checkout@v3
      with: 
        submodules: 'true'
    - name: Install choco packages
      run: |
        choco install unzip
    - name: Install regex
      run: |
        curl -L -o regex-2.7-bin.zip http://gnuwin32.sourceforge.net/downlinks/regex-bin-zip.php
        unzip -d regex-2.7-bin regex-2.7-bin.zip
        mkdir bin
        copy /y regex-2.7-bin\bin\regex2.dll bin\
    - name: Install m4
      run: |
        curl -L -o m4-1.4.14-1-bin.zip http://downloads.sourceforge.net/gnuwin32/m4-1.4.14-1-bin.zip
        unzip -d m4-1.4.14-1-bin m4-1.4.14-1-bin.zip
        copy /y m4-1.4.14-1-bin\bin\m4.exe bin\
    - name: Find MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x86
    - name: Build for release
      run: msbuild win32\z88dk.sln -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: Install perl prerequisites
      run: |
        perl -S cpan App::cpanminus
        perl -S cpanm App::Prove Capture::Tiny CPU::Z80::Assembler Data::Dump Data::HexDump File::Path List::Uniq Modern::Perl Object::Tiny::RW Regexp::Common Test::Harness Text::Diff Text::Table YAML::Tiny
    - name: Run z80asm tests
      run: |
        copy /y bin\z88dk-z80asm.exe src\z80asm\
        cd src\z80asm
        set PATH=%RUNNER_WORKSPACE%\z88dk\bin;%PATH%
        set ZCCCFG=%RUNNER_WORKSPACE%\z88dk\lib\config
        for %%i in (t\*.t)  do ( echo %%i & perl %%i )
        for %%i in (t2\*.t) do ( echo %%i & perl %%i )

